apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: InfluxDB-k6
    type: influxdb
    url: http://influxdb:8086
    database: k6
    editable: true
